### PR TITLE
1-click installer and updater. Uses micromamba to install git and conda into a contained environment (if necessary) before running the normal installation script

### PR DESCRIPTION
**Pull request by cmdr2**
Hi,

This PR enables a user to install this project without requiring them to have anaconda or git pre-installed. This reduces unnecessary friction for users who aren't programmers or very technical. If a user already has anaconda or git pre-installed, these scripts will just pass-through and won't affect them. Honestly, it's just more straightforward for a user to use. :)

## Current installation process for a user:
1. Install Anaconda
2. Install Git
3. Run the commands for a git pull (on Windows)
4. Run the webui script

## Suggested new process (for Windows and Linux):
1. Download the `install.bat` or `install.sh` script for their OS (linked below, or better, from a release on your project)
2. Run the script

That's it.

Main improvement: The user doesn't need to have python/anaconda/git pre-installed. This reduces unnecessary friction for non-technical users.

## 1-click Installers:
* Windows: https://raw.githubusercontent.com/cmdr2/hlky-webui/master/installer/install.bat
* Linux: https://raw.githubusercontent.com/cmdr2/hlky-webui/master/installer/install.sh

-----

I've tested this on Windows x64 and Linux x64. I've tested this with and without Anaconda pre-installed. I've also tested it works if the installer gets interrupted mid-way, and needs to be re-run.

**Disclosure:** I'm the author of the cmdr2 UI and 1-click installer (https://github.com/cmdr2/stable-diffusion-ui). We use a similar approach and it's been working quite well (~2k installs/day) for over 1.5 months. None of the support issue have been due to this bootstrapping process, but rather due to the usual pip failures, VPN issues, bad system config etc.

## How it works:
1. This script will install git and conda (if not found on the system PATH) using `micromamba` (an 8mb static-linked single-file binary, conda replacement). The micromamba binary will be downloaded if necessary using curl.

For users who already have git and python, this step will be skipped.

2. Next, it'll checkout the project's git repo, if necessary. On Linux, it'll download and run the [linux-sd.sh](https://raw.githubusercontent.com/JoshuaKimsey/Linux-StableDiffusion-Script/main/linux-sd.sh) script, like how the installation guide suggests.

3. Finally, it'll start `webui.cmd` on Windows. On Linux, the linux-sd.sh script takes care of this step.

After installation, users can continue running `webui.cmd` or `webui.sh` directly. It'll use either the git/python/conda that was installed through this installer, or the user's existing git/python/conda installation.

## Next steps (if you wish to adopt this)
If you're willing, then the next steps are:
1. Merging this PR will get the installer scripts into the `installer` folder
2. Uploading the installer files to a GitHub release, or using the upload links inside this PR
3. Updating the README with the download links for the installer. I can submit the PR for the README, if you're interested.

If you're interested in this, I'd definitely suggest phasing this in gradually, maybe suggested as an easier alternative on the docs, until it is judged stable to use.

Thanks! :)

# Checklist:

- [y] I have changed the base branch to `dev`
- [y] I have performed a self-review of my own code
- [y] I have commented my code in hard-to-understand areas
- [y] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by db0** [comment]
This would be a great idea!

**Comment by db0** [comment]
why not include the micromamba  binaries directly in the repo and save an extra step?

**Comment by codedealer** [comment]
> why not include the micromamba binaries directly in the PR and save an extra step to the devs?

we would like the binaries to be obtained directly from the official source anyway so that was a rational decision on OP's part.

**Comment by henk717** [comment]
Personally i would skip the seperate release files and have the bat and batch files directly in the repo. Modifying the yml to always include git. Makes it a simpler implementation and would instantly work on downstream forks.

**Comment by cmdr2** [comment]
> Personally i would skip the seperate release files and have the bat and batch files directly in the repo
That was the original plan, but would involve checking-in the micromamba binaries into this repo.

And if the user doesn't have git pre-installed, and don't have release files, then their only option is to download the repo's ZIP file. We'd then have to convert that downloaded ZIP file into a git repo somehow, so that they can get updates (via `git pull`) in the future.

> Modifying the yml to always include git
But wouldn't that require the user to have conda pre-installed (to be able to run the yml)? The idea here is to be able to install this even on PCs that don't have conda and git.

**Comment by ZeroCool940711** [comment]
@cmdr2 do you think this PR is ready to be merged into dev or it still needs more work?

**Comment by cmdr2** [comment]
@ZeroCool940711 

I'm running a few more tests, and will move it out of draft status hopefully in 24 hours.

After that, it can be merged into the `dev` branch.

In the meanwhile, it would be really helpful if people from Sygil could test on their Windows and Linux machines as well. They can download and run the installers I linked in the first post of this PR.

This is because the bootstrapping part is common with our repo, but the rest of the code is custom to the Sygil repo. So it needs to be tested well.

**Comment by ZeroCool940711** [comment]
@cmdr2 I will test things and let you know if they work, I can test it on Windows 10 and then use WSL to test it on Linux, I will test it when I wake up tomorrow as I'm about to sleep tho, also, there is one big thing we are about to do, we will move the `webui.cmd` and other stuff related to gradio to be "legacy" to make it clear that it's an old version and there is a new one available, we'll make then the streamlit version the main one, so, do you want me to hold that until after we merge your PR so we can just get this done first and then do that or you want us to do it first and then to make sure things work after the changes with the installer on this PR?

**Comment by cmdr2** [comment]
@ZeroCool940711 Thanks. All this script does is to ensure that conda and git exist on the system PATH. So it shouldn't really affect things post the change.

The only change this PR makes to webui.cmd and webui.sh is to ensure that it knows about conda (if installed by the installer).

At this moment, I'd say this PR can go first, before the webui deprecation. I can help with any necessary changes once webui.cmd is deprecated, I'm active on Discord (in the #roundtable channel).

So far all the tests look okay on my end. I'm waiting for the test results with some other users as well (using people on our cmdr2 UI repo). Will change the PR status within a day if looks good. :)

**Comment by henk717** [comment]
The nataili branch already uses my own implementation of a micromamba runtime that is a lot more simplistic, that implementation uses files inside the repo rather than a seperate installer batch so people can obtain the repo by any means and it also works with forks and cloned repositories more easily.

I have made this implementation portable so porting it to this branch is a trivial task, so if an overhaul is planned either way with the files moving to a legacy folder we could very easily hook it up to the same implementation.

So its also a question if we would like to keep these implementations similar, because otherwise you will get two repositories use completely different methods.

Instead of all the conda checks leveraging existing conda installations the user may have mine is fully self contained, purposefully ignoring other runtimes and installations on the PC to avoid any conflicts that may arrise from them.

What prevents me from issuing a PR with my own implementation is twofold.
1. This attempt with the installer already exists, and to me it is up to the community to decide which approach is more desirable for this branch.
2. I need to know what is desirable with the existing files, we could force the new runtime using my implementation for example which would result in a redownload for everyone but then also results in this being contained and clean from then on. Alternatively I would have to make a seperate file for the runtime versions, in which case cmdr2's script seems more fitting.

**Comment by ZeroCool940711** [comment]
@cmdr2 I tested the install scripts and they seem to be working both on Windows and Linux, about the models/weights being downloaded by the script I think it won't be necessary soon as we have a backend called [Nataili](https://github.com/Sygil-Dev/nataili) that handles downloading the models if they are not already downloaded, I just need to move things to use it instead of the old Model Manager we were using which needed things to be done manually. I think the PR is ready to be merged, I would say that we only need to change the url to point to our repo instead of yours but that can be done after merging the PR.

**Comment by cmdr2** [comment]
Thanks @ZeroCool940711 I've marked this as ready for review.

**Review by ZeroCool940711 — APPROVED** [review]
Looks good to me, I think we can merge it.

**Comment by ZeroCool940711** [comment]
Merged. I think we can address any issue and improve things over time if there are any issues with it.

**Comment by cmdr2** [comment]
Sure, I'm around on Discord (cmdr2 #2190) and in the #roundtable channel on the Sygil server. Happy to help!

**Pull request merged**
