### PR TITLE
Curly brace syntax for generating prompt combinations

### PR DESCRIPTION
**Pull request by StuartRiffle**
# Description
This is a different syntax for generating prompt variations.  It generates all combinations, like the existing prompt matrix functionality, but allows multiple, independent sets of variations.

For example the prompt:

		A {red|blue} {dog|cat}

...would generate these 4 variations:

		A red dog
		A red cat
		A blue dog
		A blue cat

Something like this:
2022-09-13 13_32_41-Stable Diffusion WebUI

Notes:
- Empty strings are allowed; they are just removed from the generated prompt
- This is more flexible than the | syntax for kicking off complicated batches, but also more ugly
- This should probably be a top-level toggle so that users can disable it, if they want to preserve curly braces in their prompts

# Checklist:

- [x] I have changed the base branch to `dev`
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

(If you end up using this PR, I will hunt down the associated docs and update them, please lmk)

### CODE REVIEW

**Comment by TinyBeeman** [comment]
This already exists:
` @A (red|blue) (dog|cat)`

**Comment by TinyBeeman** [comment]
You have to turn on Multi-prompt, and I haven't tested it in Streamlit to make sure it works.

**Comment by dudumaroja** [comment]
yes, this already exists (promp matrix) just the grid it generates need some adjustments.

**Comment by blanelegant** [comment]
@TinyBeeman Is there documentation for this existing functionality?

**Pull request closed without merging**
